In [3]:
import numpy as np
from KEFRiN import *
from sklearn import metrics
import processing_tools as pt

### Load dataset

In [4]:
p = np.load("/Users/admin/Desktop/nitin/CS274/Data/Wiki/p.npy")
y = np.load("/Users/admin/Desktop/nitin/CS274/Data/Wiki/y.npy")
gt = np.load("/Users/admin/Desktop/nitin/CS274/Data/Wiki/gt.npy")

print(p.shape, y.shape, gt.shape)

(2405, 2405) (2405, 4973) (2405,)


In [5]:
np.unique(gt)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

### preprocessing the data

In [6]:
p_, _, p_z, _, p_rng, _, _,_,_,_,_,_ = pt.preprocess_p(p)
y_, _, y_z, _, y_rng, _, = pt.preprocess_y(y_in=y, data_type='C')

In [7]:
gt

array([8, 8, 8, ..., 8, 8, 8])

## Applying KEFRiN

### KEFRiNe

In [8]:
KEFRiNe_results = EkifenMin(y=y_, p=p_, rho=1, xi=1,
                         n_clusters=17, kmean_pp=1, euclidean=1,
                         cosine=0, max_iteration=1000,manhattan=0).apply_ekifen()

In [9]:
KEFRiNe_results

array([0, 0, 0, ..., 0, 0, 0])


### KEFRiNc

In [10]:
KEFRiNc_results = EkifenMin(y=y_, p=p_, rho=1, xi=1,
                         n_clusters=17, kmean_pp=1, euclidean=0,
                         cosine=1, max_iteration=1000,manhattan=0).apply_ekifen()

In [11]:
KEFRiNc_results

array([14,  2, 14, ..., 14,  2,  4])

## Results

In [12]:
print("KEFRiNe ARI:", metrics.adjusted_rand_score(gt, KEFRiNe_results))
print("KEFRiNe NMI", metrics.normalized_mutual_info_score(gt,KEFRiNe_results))

KEFRiNe ARI: 0.00520070438657368
KEFRiNe NMI 0.05930440914790197


In [13]:
print("KEFRiNc ARI:", metrics.adjusted_rand_score(gt, KEFRiNc_results))
print("KEFRiNc NMI", metrics.normalized_mutual_info_score(gt,KEFRiNc_results))

KEFRiNc ARI: 0.21800136992998215
KEFRiNc NMI 0.3846064536245635
